// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/EditItem copy.vue')['default']
    EditItem: typeof import('./components/EditItem.vue')['default']
    NewItem: typeof import('./components/NewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheModal: typeof import('./components/TheModal.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
  }
}
